services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /opt/keycloak/bin/kc.sh start-dev --import-realm &
        until echo > /dev/tcp/localhost/8080; do sleep 2; done
        sleep 5
        /opt/keycloak/bin/kcadm.sh config credentials \
          --server http://localhost:8080 \
          --realm master \
          --user mcc-admin \
          --password uworbital
        /opt/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE
        wait
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: mcc-admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: uworbital
      KC_HEALTH_ENABLED: true
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./backend/app/mcc_keycloak/mcc-realm.json:/opt/keycloak/data/import/mcc-realm.json

volumes:
  keycloak_data:
