services:
  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/backend
      - GS_DATABASE_LOCATION=host.docker.internal
  aro-frontend:
    build:
      context: frontend/aro
      dockerfile: Dockerfile.aro
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend/aro:/app
      - /app/node_modules
  mcc-frontend:
    build:
      context: frontend/mcc
      dockerfile: Dockerfile.mcc
    ports:
      - "5174:5174"
    working_dir: /app
    volumes:
      - ./frontend/mcc:/app
      - /app/node_modules
    env_file:
      - .env
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${GS_DATABASE_USER}
      POSTGRES_PASSWORD: ${GS_DATABASE_PASSWORD}
      POSTGRES_DB: ${GS_DATABASE_NAME}
    ports:
      - "${GS_DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
