"""
verification_email.py

Builds and sends the ARO email verification message handed to
`AROUserManager.on_after_request_verify`.
"""

from pydantic import NameEmail

from app.config.env_settings.backend_config import settings
from app.utils.email import Email, EmailType, send

VERIFY_EMAIL_SUBJECT = "Verify your ARO account"
VERIFY_EMAIL_ROUTE = "/verify"


def verification_link(token: str) -> str:
    """
    Build the ARO frontend link that carries the verification token.

    :param token: verification token generated by the fastapi-users manager
    :return: absolute URL of the ARO verify page, pre-filled with the token
    """
    return f"{settings.auth.frontend_url.rstrip('/')}{VERIFY_EMAIL_ROUTE}?token={token}"


async def send_verification_email(email: str, token: str) -> None:
    """
    Email an ARO user the code (and one-click link) that verifies their address.

    :param email: address of the ARO user requesting verification
    :param token: verification token generated by the fastapi-users manager
    """
    link = verification_link(token)

    message = Email(
        subject=VERIFY_EMAIL_SUBJECT,
        # The ARO user record carries no display name, so the address doubles as one.
        recipients=[NameEmail(name=email, email=email)],
        type=EmailType.EMAIL_VERIFICATION,
        text=(
            "Welcome to the UW Orbital Amateur Radio Operator (ARO) program!\n\n"
            f"Enter this verification code to confirm your email address:\n\n{token}\n\n"
            f"Or confirm it straight away: {link}\n"
        ),
        html=(
            "<p>Welcome to the UW Orbital Amateur Radio Operator (ARO) program!</p>"
            "<p>Enter this verification code to confirm your email address:</p>"
            f"<p><strong>{token}</strong></p>"
            f'<p><a href="{link}">Confirm my email address</a></p>'
        ),
    )

    await send(message)
