"""
Encoder/decoder for the OBC compact binary log format.

The satellite logs in a compact binary format to reduce downlink size (see
OBC-firmware obc/shared/logging/obc_logging_codec.h). Each record replaces the
file path with a file ID and the log level name with a 3-bit level ID. This
module decodes the binary records back into the standard human-readable text
log format, and can also encode/parse the existing text format (useful for
testing and for converting old text logs).

Binary record layout (little-endian):

| Offset | Size | Field                                                  |
|--------|------|--------------------------------------------------------|
| 0      | 1    | Sync byte (0xA8)                                       |
| 1      | 1    | Flags: bits 0-2 level, bit 3 type (0 = error code,     |
|        |      | 1 = msg), bit 4 has-timestamp                          |
| 2      | 2    | File ID (index into log_file_ids.json)                 |
| 4      | 2    | Line number                                            |
| 6      | 4    | Unix timestamp (only if has-timestamp flag set)        |
| ...    | 4    | Error code (only if type is error code)                |
| ...    | 1+N  | Msg length N + N msg bytes (only if type is msg)       |

The file ID mapping (log_file_ids.json) is generated in the OBC-firmware repo
by scripts/gen_log_file_ids.py and must be kept in sync with the firmware
build that produced the logs.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

SYNC_BYTE = 0xA8

FLAG_LEVEL_MASK = 0x07
FLAG_TYPE_MSG = 0x08
FLAG_HAS_TIMESTAMP = 0x10

FIXED_HEADER_SIZE = 6
TIMESTAMP_SIZE = 4
ERROR_CODE_SIZE = 4
MAX_MSG_LEN = 128

FILE_ID_UNKNOWN = 0xFFFF

LEVEL_NAMES = ("TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL")

_FILE_IDS_PATH = Path(__file__).resolve().parent / "log_file_ids.json"

# Matches the firmware text log format in all three timestamp modes:
#   "25-01-01_00-00-00 ERROR -> path/file.c:123 - 301"  (LOG_DATE_TIME)
#   "1735689600 ERROR -> path/file.c:123 - 301"         (LOG_UNIX)
#   "ERROR -> path/file.c:123 - some message"           (no timestamp)
_TEXT_LINE_RE = re.compile(
    r"^(?:(?P<dt>\d{2}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2})\s+|(?P<unix>\d+)\s+)?"
    r"(?P<level>TRACE|DEBUG|INFO|WARN|ERROR|FATAL)\s*->\s*"
    r"(?P<path>\S+):(?P<line>\d+)\s+-\s+(?P<payload>.*?)\s*$"
)


class LogCodecError(Exception):
    """Raised when a binary log record or a text log line cannot be parsed."""


@dataclass
class LogEntry:
    """A single decoded log record."""

    level: int
    is_msg: bool
    file_id: int
    line: int
    timestamp: int | None = None  # Unix seconds
    err_code: int | None = None  # Set when is_msg is False
    msg: str | None = None  # Set when is_msg is True
    file_path: str | None = None  # Resolved from file_id (or parsed from text)

    @property
    def level_name(self) -> str:
        """Return the log level name (e.g. "ERROR")."""
        return LEVEL_NAMES[self.level]


def load_file_id_mapping(path: Path = _FILE_IDS_PATH) -> list[str]:
    """
    Load the file ID -> file path mapping generated by the OBC-firmware repo.

    The file's index in the returned list is its ID.
    """
    with open(path) as f:
        data = json.load(f)
    files: list[str] = data["files"]
    return files


_file_paths: list[str] | None = None


def _get_file_paths() -> list[str]:
    global _file_paths
    if _file_paths is None:
        _file_paths = load_file_id_mapping()
    return _file_paths


def file_path_from_id(file_id: int) -> str | None:
    """Return the repo-relative file path for a file ID, or None if unknown."""
    paths = _get_file_paths()
    if 0 <= file_id < len(paths):
        return paths[file_id]
    return None


def file_id_from_path(path: str) -> int:
    """Return the file ID for a repo-relative file path, or FILE_ID_UNKNOWN."""
    paths = _get_file_paths()
    try:
        return paths.index(path)
    except ValueError:
        return FILE_ID_UNKNOWN


def encode_log_entry(entry: LogEntry) -> bytes:
    """Encode a log entry into the compact binary format used by the OBC."""
    if not 0 <= entry.level < len(LEVEL_NAMES):
        raise LogCodecError(f"Invalid log level: {entry.level}")

    flags = entry.level & FLAG_LEVEL_MASK
    if entry.is_msg:
        flags |= FLAG_TYPE_MSG
    if entry.timestamp is not None:
        flags |= FLAG_HAS_TIMESTAMP

    record = bytearray([SYNC_BYTE, flags])
    record += entry.file_id.to_bytes(2, "little")
    record += min(entry.line, 0xFFFF).to_bytes(2, "little")

    if entry.timestamp is not None:
        record += entry.timestamp.to_bytes(4, "little")

    if entry.is_msg:
        msg_bytes = (entry.msg or "").encode("utf-8")[:MAX_MSG_LEN]
        record += len(msg_bytes).to_bytes(1, "little")
        record += msg_bytes
    else:
        record += (entry.err_code or 0).to_bytes(4, "little")

    return bytes(record)


def decode_log_entry(data: bytes, offset: int = 0) -> tuple[LogEntry, int]:
    """
    Decode a single binary log record starting at data[offset].

    Returns the decoded entry and the number of bytes consumed.
    Raises LogCodecError if the record is malformed or truncated.
    """
    buf = data[offset:]
    if len(buf) < FIXED_HEADER_SIZE:
        raise LogCodecError("Buffer too short for log record header")
    if buf[0] != SYNC_BYTE:
        raise LogCodecError(f"Bad sync byte: 0x{buf[0]:02X}")

    flags = buf[1]
    level = flags & FLAG_LEVEL_MASK
    if level >= len(LEVEL_NAMES):
        raise LogCodecError(f"Invalid log level: {level}")

    is_msg = bool(flags & FLAG_TYPE_MSG)
    has_timestamp = bool(flags & FLAG_HAS_TIMESTAMP)
    file_id = int.from_bytes(buf[2:4], "little")
    line = int.from_bytes(buf[4:6], "little")

    pos = FIXED_HEADER_SIZE
    timestamp = None
    if has_timestamp:
        if len(buf) < pos + TIMESTAMP_SIZE:
            raise LogCodecError("Buffer too short for timestamp")
        timestamp = int.from_bytes(buf[pos : pos + TIMESTAMP_SIZE], "little")
        pos += TIMESTAMP_SIZE

    err_code = None
    msg = None
    if is_msg:
        if len(buf) < pos + 1:
            raise LogCodecError("Buffer too short for msg length")
        msg_len = buf[pos]
        pos += 1
        if msg_len > MAX_MSG_LEN or len(buf) < pos + msg_len:
            raise LogCodecError("Buffer too short for msg body")
        msg = buf[pos : pos + msg_len].decode("utf-8", errors="replace")
        pos += msg_len
    else:
        if len(buf) < pos + ERROR_CODE_SIZE:
            raise LogCodecError("Buffer too short for error code")
        err_code = int.from_bytes(buf[pos : pos + ERROR_CODE_SIZE], "little")
        pos += ERROR_CODE_SIZE

    entry = LogEntry(
        level=level,
        is_msg=is_msg,
        file_id=file_id,
        line=line,
        timestamp=timestamp,
        err_code=err_code,
        msg=msg,
        file_path=file_path_from_id(file_id),
    )
    return entry, pos


def decode_log_stream(data: bytes) -> list[LogEntry]:
    """
    Decode all binary log records in a byte stream.

    Resynchronizes on the next sync byte after corrupted/unparseable data, so a
    bad record doesn't drop the whole stream.
    """
    entries: list[LogEntry] = []
    pos = 0
    while pos < len(data):
        if data[pos] != SYNC_BYTE:
            pos += 1
            continue
        try:
            entry, consumed = decode_log_entry(data, pos)
        except LogCodecError:
            pos += 1
            continue
        entries.append(entry)
        pos += consumed
    return entries


def entry_to_text(entry: LogEntry, unix_style: bool = False) -> str:
    """
    Render a log entry in the firmware's text log format (without trailing CRLF).

    Matches logger.c's output: "[timestamp ]LEVEL -> file:line - payload".
    By default the timestamp is rendered as a datetime (LOG_DATE_TIME format);
    pass unix_style=True for the raw unix-seconds prefix (LOG_UNIX format).
    """
    path = entry.file_path or file_path_from_id(entry.file_id) or f"<file:{entry.file_id}>"
    payload = entry.msg if entry.is_msg else str(entry.err_code)
    prefix = ""
    if entry.timestamp is not None:
        if unix_style:
            prefix = f"{entry.timestamp} "
        else:
            dt = datetime.fromtimestamp(entry.timestamp, tz=UTC)
            prefix = f"{dt.year % 100:02d}-{dt.month:02d}-{dt.day:02d}_{dt.hour:02d}-{dt.minute:02d}-{dt.second:02d} "
    return f"{prefix}{entry.level_name:<5} -> {path}:{entry.line} - {payload}"


def parse_text_log_line(line: str) -> LogEntry:
    """
    Parse a line in the firmware's text log format into a LogEntry.

    Supports all three firmware timestamp modes (datetime, unix, none). A
    payload consisting only of digits is treated as an error code, matching how
    the firmware prints error codes as raw integers.
    """
    match = _TEXT_LINE_RE.match(line.strip())
    if match is None:
        raise LogCodecError(f"Unparseable log line: {line!r}")

    timestamp: int | None = None
    if match["dt"] is not None:
        yy, mm, dd = (int(x) for x in match["dt"][:8].split("-"))
        hh, mi, ss = (int(x) for x in match["dt"][9:].split("-"))
        timestamp = int(datetime(2000 + yy, mm, dd, hh, mi, ss, tzinfo=UTC).timestamp())
    elif match["unix"] is not None:
        timestamp = int(match["unix"])

    payload = match["payload"]
    is_msg = not payload.isdigit()
    path = match["path"]

    return LogEntry(
        level=LEVEL_NAMES.index(match["level"]),
        is_msg=is_msg,
        file_id=file_id_from_path(path),
        line=int(match["line"]),
        timestamp=timestamp,
        err_code=None if is_msg else int(payload),
        msg=payload if is_msg else None,
        file_path=path,
    )


def main(argv: list[str]) -> int:
    """Decode a binary log file to text: python -m obc_utils.log_codec <log.bin>."""
    if len(argv) != 2:
        print("Usage: python -m obc_utils.log_codec <binary-log-file>", file=sys.stderr)
        return 1
    data = Path(argv[1]).read_bytes()
    for entry in decode_log_stream(data):
        print(entry_to_text(entry))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
