from typing import Final
from uuid import UUID

from pydantic import EmailStr
from sqlmodel import Field

from app.config.data_values import DEFAULT_MAX_LENGTH
from app.data.enums.mcc_users import MCCAdminRequestStatus
from app.data.models.base_model import BaseSQLModel

MCC_USER_SCHEMA_NAME: Final[str] = "mcc_users"
MCC_USER_TABLE_NAME: Final[str] = "users_data"


class MCCUsers(BaseSQLModel, table=True):
    """
    Stores all the information about an MCC user

    :param id: MCC User ID. NOT AUTOGENERATED. Provided by Keycloak authentication.
    :type id: UUID
    :param email: Valid email
    :type email: EmailStr
    :param first_name: First name of MCC user
    :type first_name: str, None
    :param last_name: Last name of MCC user
    :type last_name: str, None
    :param phone_number: Valid phone number
    :type phone_number: str, None
    :param admin_request_status: Status of the user's request for MCC admin access
    :type admin_request_status: MCCAdminRequestStatus
    """

    id: UUID = Field(primary_key=True, index=True, description="UUID sub given from decoded Keycloak ID Token.")
    email: EmailStr = Field(max_length=DEFAULT_MAX_LENGTH)
    first_name: str | None = Field(max_length=DEFAULT_MAX_LENGTH, nullable=True, default=None)
    last_name: str | None = Field(max_length=DEFAULT_MAX_LENGTH, nullable=True, default=None)
    phone_number: str | None
    admin_request_status: MCCAdminRequestStatus = Field(default=MCCAdminRequestStatus.NOT_REQUESTED)

    # table information
    __tablename__ = MCC_USER_TABLE_NAME
    __table_args__ = {"schema": MCC_USER_SCHEMA_NAME}
