"""aro fastapi users auth base migration

Revision ID: 18263e005b66
Revises: b8e4c02f1d67
Create Date: 2026-08-15 11:01:51.589451

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18263e005b66'
down_revision = 'b8e4c02f1d67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('family_id', sa.Uuid(), nullable=False), schema='aro_users')
    op.add_column('auth_tokens', sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='aro_users')
    op.add_column('auth_tokens', sa.Column('rotated_at', sa.DateTime(), nullable=True), schema='aro_users')
    op.add_column('auth_tokens', sa.Column('revoked_at', sa.DateTime(), nullable=True), schema='aro_users')
    op.create_index(op.f('ix_aro_users_auth_tokens_family_id'), 'auth_tokens', ['family_id'], unique=False, schema='aro_users')
    op.create_index(op.f('ix_aro_users_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True, schema='aro_users')
    op.drop_column('auth_tokens', 'type', schema='aro_users')
    op.drop_column('auth_tokens', 'token', schema='aro_users')
    # drop_column doesn't drop the underlying Postgres enum type
    op.execute('DROP TYPE IF EXISTS auth_type')
    op.alter_column('user_login', 'password_salt',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               schema='aro_users')
    op.alter_column('user_login', 'hashing_algorithm_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='aro_users')
    op.alter_column('user_login', 'email_verification_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               schema='aro_users')
    op.add_column('users_data', sa.Column('is_active', sa.Boolean(), nullable=False), schema='aro_users')
    op.add_column('users_data', sa.Column('is_superuser', sa.Boolean(), nullable=False), schema='aro_users')
    op.drop_index(op.f('ix_aro_users_users_data_google_id'), table_name='users_data', schema='aro_users')
    op.drop_column('users_data', 'google_id', schema='aro_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_data', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True), schema='aro_users')
    op.create_index(op.f('ix_aro_users_users_data_google_id'), 'users_data', ['google_id'], unique=True, schema='aro_users')
    op.drop_column('users_data', 'is_superuser', schema='aro_users')
    op.drop_column('users_data', 'is_active', schema='aro_users')
    op.alter_column('user_login', 'email_verification_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               schema='aro_users')
    op.alter_column('user_login', 'hashing_algorithm_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='aro_users')
    op.alter_column('user_login', 'password_salt',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               schema='aro_users')
    op.add_column('auth_tokens', sa.Column('token', sa.UUID(), autoincrement=False, nullable=False), schema='aro_users')
    op.add_column('auth_tokens', sa.Column('type', postgresql.ENUM('GOOGLE_OAUTH', 'EMAIL_PASSWORD', 'DUMMY', 'ANOTHERDUMMY', 'TEST', name='auth_type'), autoincrement=False, nullable=False), schema='aro_users')
    op.drop_index(op.f('ix_aro_users_auth_tokens_token_hash'), table_name='auth_tokens', schema='aro_users')
    op.drop_index(op.f('ix_aro_users_auth_tokens_family_id'), table_name='auth_tokens', schema='aro_users')
    op.drop_column('auth_tokens', 'revoked_at', schema='aro_users')
    op.drop_column('auth_tokens', 'rotated_at', schema='aro_users')
    op.drop_column('auth_tokens', 'token_hash', schema='aro_users')
    op.drop_column('auth_tokens', 'family_id', schema='aro_users')
    # ### end Alembic commands ###
