"""
add logs.api table

Revision ID: 43af3244c68b
Revises: 6c54d182bb55
Create Date: 2026-03-28 00:00:29.295441

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "43af3244c68b"
down_revision = "6c54d182bb55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS logs")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("msg", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("module", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("function_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="logs",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api", schema="logs")
    op.execute("DROP SCHEMA IF EXISTS logs")
    # ### end Alembic commands ###
