"""add session_id to commands

Revision ID: 497abb829bde
Revises: 78fc5fa51aba
Create Date: 2026-07-12 20:21:11.175309

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '497abb829bde'
down_revision = '78fc5fa51aba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commands', sa.Column('session_id', sa.Uuid(), nullable=False), schema='transactional')
    op.create_foreign_key(None, 'commands', 'sessions', ['session_id'], ['id'], source_schema='transactional', referent_schema='transactional', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commands', schema='transactional', type_='foreignkey')
    op.drop_column('commands', 'session_id', schema='transactional')
    # ### end Alembic commands ###
