"""add google_id to users_data

Revision ID: 514ae47263fe
Revises: 6c54d182bb55
Create Date: 2026-03-13 18:55:05.837412

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '514ae47263fe'
down_revision = '6c54d182bb55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('password_salt', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False), schema='aro_users')
    op.drop_column('user_login', 'salt', schema='aro_users')
    op.add_column('users_data', sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='aro_users')
    op.add_column('users_data', sa.Column('is_callsign_verified', sa.Boolean(), nullable=False), schema='aro_users')
    op.alter_column('users_data', 'call_sign',
               existing_type=sa.VARCHAR(length=6),
               nullable=True,
               schema='aro_users')
    op.alter_column('users_data', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='aro_users')
    op.create_index(op.f('ix_aro_users_users_data_google_id'), 'users_data', ['google_id'], unique=True, schema='aro_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aro_users_users_data_google_id'), table_name='users_data', schema='aro_users')
    op.alter_column('users_data', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='aro_users')
    op.alter_column('users_data', 'call_sign',
               existing_type=sa.VARCHAR(length=6),
               nullable=False,
               schema='aro_users')
    op.drop_column('users_data', 'is_callsign_verified', schema='aro_users')
    op.drop_column('users_data', 'google_id', schema='aro_users')
    op.add_column('user_login', sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=False), schema='aro_users')
    op.drop_column('user_login', 'password_salt', schema='aro_users')
    # ### end Alembic commands ###
