"""update session end time to non nullable

Revision ID: 551e1cea7b28
Revises: e1f3cdd739d7
Create Date: 2026-07-15 23:14:08.580979

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '551e1cea7b28'
down_revision = 'e1f3cdd739d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='transactional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='transactional')
    # ### end Alembic commands ###
