"""add missing aro auth foreign keys and timezone aware timestamps

Revision ID: 5ca1f847cae4
Revises: 18263e005b66
Create Date: 2026-08-15 19:28:09.929705

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ca1f847cae4'
down_revision = '18263e005b66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_tokens', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='aro_users')
    op.alter_column('auth_tokens', 'expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='aro_users')
    op.alter_column('auth_tokens', 'rotated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='aro_users')
    op.alter_column('auth_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='aro_users')
    op.create_foreign_key(None, 'auth_tokens', 'users_data', ['user_id'], ['id'], source_schema='aro_users', referent_schema='aro_users')
    op.alter_column('user_login', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='aro_users')
    op.create_unique_constraint(None, 'user_login', ['user_id'], schema='aro_users')
    op.create_foreign_key(None, 'user_login', 'users_data', ['user_id'], ['id'], source_schema='aro_users', referent_schema='aro_users')
    op.drop_column('user_login', 'password_salt', schema='aro_users')
    op.drop_column('user_login', 'hashing_algorithm_name', schema='aro_users')
    op.drop_column('user_login', 'email_verification_token', schema='aro_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('email_verification_token', sa.VARCHAR(length=200), autoincrement=False, nullable=True), schema='aro_users')
    op.add_column('user_login', sa.Column('hashing_algorithm_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='aro_users')
    op.add_column('user_login', sa.Column('password_salt', sa.VARCHAR(length=32), autoincrement=False, nullable=True), schema='aro_users')
    op.drop_constraint(None, 'user_login', schema='aro_users', type_='foreignkey')
    op.drop_constraint(None, 'user_login', schema='aro_users', type_='unique')
    op.alter_column('user_login', 'created_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='aro_users')
    op.drop_constraint(None, 'auth_tokens', schema='aro_users', type_='foreignkey')
    op.alter_column('auth_tokens', 'revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='aro_users')
    op.alter_column('auth_tokens', 'rotated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='aro_users')
    op.alter_column('auth_tokens', 'expiry',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='aro_users')
    op.alter_column('auth_tokens', 'created_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='aro_users')
    # ### end Alembic commands ###
