"""add missing migrations

Revision ID: 78fc5fa51aba
Revises: c7f2a91b4d3e
Create Date: 2026-07-12 20:20:58.302690

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '78fc5fa51aba'
down_revision = 'c7f2a91b4d3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_login', 'password',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=False,
               schema='aro_users')
    op.alter_column('user_login', 'hashing_algorithm_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False,
               schema='aro_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_login', 'hashing_algorithm_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False,
               schema='aro_users')
    op.alter_column('user_login', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               schema='aro_users')
    # ### end Alembic commands ###
