"""add logs.api table

Revision ID: 7a8ddc58f61d
Revises: f3a9c1d24b70
Create Date: 2026-09-02 15:21:13.533603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7a8ddc58f61d'
down_revision = 'f3a9c1d24b70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS logs;")
    op.create_table('api',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('function', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='logs'
    )
    op.create_index(op.f('ix_logs_api_time'), 'api', ['time'], unique=False, schema='logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_api_time'), table_name='api', schema='logs')
    op.drop_table('api', schema='logs')
    op.execute("DROP SCHEMA IF EXISTS logs;")
    # ### end Alembic commands ###
