"""make timestamps timezone aware

Revision ID: 97bda742ad0d
Revises: 497abb829bde
Create Date: 2026-07-15 23:05:45.187281

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97bda742ad0d'
down_revision = '497abb829bde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='transactional')
    op.alter_column('sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               schema='transactional')
    op.drop_constraint(op.f('comms_session_end_time_key'), 'sessions', schema='transactional', type_='unique')
    op.drop_constraint(op.f('comms_session_start_time_key'), 'sessions', schema='transactional', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('comms_session_start_time_key'), 'sessions', ['start_time'], schema='transactional', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('comms_session_end_time_key'), 'sessions', ['end_time'], schema='transactional', postgresql_nulls_not_distinct=False)
    op.alter_column('sessions', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               schema='transactional')
    op.alter_column('sessions', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='transactional')
    # ### end Alembic commands ###
