"""add logs.api table

Revision ID: a1b2c3d4e5f6
Revises: f3a9c1d24b70
Create Date: 2026-08-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f3a9c1d24b70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS logs;")
    op.create_table(
        'api',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('function', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('line', sa.Integer(), nullable=True),
        sa.Column('extra', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='logs',
    )
    op.create_index(op.f('ix_logs_api_id'), 'api', ['id'], unique=False, schema='logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_api_id'), table_name='api', schema='logs')
    op.drop_table('api', schema='logs')
    op.execute("DROP SCHEMA IF EXISTS logs;")
    # ### end Alembic commands ###
