"""make every timestamp timezone aware

Revision ID: e1f3cdd739d7
Revises: 97bda742ad0d
Create Date: 2026-07-15 23:12:05.347764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1f3cdd739d7'
down_revision = '97bda742ad0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aro_requests', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='transactional')
    op.alter_column('aro_requests', 'request_sent_to_obc_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='transactional')
    op.alter_column('aro_requests', 'pic_taken_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='transactional')
    op.alter_column('aro_requests', 'pic_transmitted_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='transactional')
    op.alter_column('commands', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='transactional')
    op.alter_column('packets', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='transactional')
    op.alter_column('sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='transactional')
    op.alter_column('telemetry', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='transactional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telemetry', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='transactional')
    op.alter_column('sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='transactional')
    op.alter_column('packets', 'created_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='transactional')
    op.alter_column('commands', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='transactional')
    op.alter_column('aro_requests', 'pic_transmitted_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='transactional')
    op.alter_column('aro_requests', 'pic_taken_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='transactional')
    op.alter_column('aro_requests', 'request_sent_to_obc_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='transactional')
    op.alter_column('aro_requests', 'created_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='transactional')
    # ### end Alembic commands ###
