# data/tables/log_tables.py

from datetime import datetime  # Python's built-in datetime type — used for the timestamp column
from typing import Final       # Final means the value can never be reassigned (like a constant)
from sqlmodel import Field     # Field() lets us configure column options (primary key, nullable, etc.)
from data.tables.base_model import BaseSQLModel  # Our custom base class — all tables extend this

# ---------------------------------------------------------------------------
# Constants — same pattern as aro_user_tables.py and main_tables.py
# Using Final[str] means Python will warn you if you accidentally reassign them
# ---------------------------------------------------------------------------
LOGS_SCHEMA_NAME: Final[str] = "logs"   # The PostgreSQL schema (like a namespace / folder for tables)
LOGS_API_TABLE_NAME: Final[str] = "api" # The actual table name inside that schema → logs.api


# ---------------------------------------------------------------------------
# The table class — this IS the table definition
# SQLModel reads this class and knows exactly what columns to create in Postgres
# The ", table=True" part tells SQLModel: "this is a real DB table, not just a data shape"
# ---------------------------------------------------------------------------
class APILog(BaseSQLModel, table=True):
    """
    Stores structured log records from the loguru logger.

    Each row = one log event emitted by the application.
    This replaces the previous file-based logging sink.
    """

    # ------------------------------------------------------------------
    # id — the primary key
    # Every table needs one. auto-generated by the DB (auto-increment).
    # Optional[int] = None means Python doesn't need to supply it — Postgres will.
    # ------------------------------------------------------------------
    id: int | None = Field(default=None, primary_key=True)

    # ------------------------------------------------------------------
    # time — when the log was emitted
    # default_factory=datetime.utcnow means: "fill this in automatically
    # with the current UTC time if nothing is provided"
    # ------------------------------------------------------------------
    time: datetime = Field(default_factory=datetime.utcnow)

    # ------------------------------------------------------------------
    # level — the log severity as a string
    # e.g. "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
    # loguru calls this the log "level name"
    # ------------------------------------------------------------------
    level: str = Field(max_length=20)

    # ------------------------------------------------------------------
    # msg — the actual log message
    # We use str with no max_length here because log messages can be long.
    # SQLModel will map this to TEXT in Postgres (no length limit).
    # ------------------------------------------------------------------
    msg: str

    # ------------------------------------------------------------------
    # module — which Python file the log came from
    # e.g. "backend_setup" or "lifespan"
    # loguru provides this automatically via its `record` object
    # ------------------------------------------------------------------
    module: str = Field(max_length=100)

    # ------------------------------------------------------------------
    # function_name — which function inside that file emitted the log
    # e.g. "setup_logging" or "startup"
    # ------------------------------------------------------------------
    function_name: str = Field(max_length=100)

    # ------------------------------------------------------------------
    # line_no — the exact line number in the source file
    # Useful for debugging — you can jump straight to the offending line
    # ------------------------------------------------------------------
    line_no: int

    # ------------------------------------------------------------------
    # __tablename__ and __table_args__ — tells SQLModel/SQLAlchemy the
    # exact table name and schema to use in Postgres.
    # Without __table_args__, it would create the table in the default
    # "public" schema instead of the "logs" schema.
    # ------------------------------------------------------------------
    __tablename__ = LOGS_API_TABLE_NAME
    __table_args__ = {"schema": LOGS_SCHEMA_NAME}